---
title: "The relationship between plant generalism and the benefit of pollination"
author: "Fernando Cagua, Hugo Marrero, Jason Tylianakis, Daniel Stouffer"
output:
  word_document: default
  html_document: default
---

The reproduction of angiosperms relies to a large extent on the service provided by pollinators. 
It has been shown that the quality of the pollination service in a plant community increases with the diversity of the pollinator species. 
However, it is also true that interacting with a large number of pollinator species is not always beneficial. 
One reason for this is that plants that interact with a large number of species are more likely to suffer from interspecific pollen transfer, which reduces the overall quality of the pollination service they receive. 
Although this trade-off has been implicitly or explicitly incorporated in several models of pollination, it has never been empirically tested at the community level. 
Here I use visitation, abundance, and pollen-deposition data from eleven pollination communities in the Argentinean pampa to test whether this trade-off is observable. 
Contrary to our expectation, we did not find a negative relationship between the number of partners of a plant and the proportion of conspecific pollen found in the flower's stigma. 
Instead, we found that generalist plants—which were generally more abundant—tend to produce greater amounts of pollen, were less dependent on animal pollination, and were less susceptible to receive heterospecific pollen. 
Overall our findings suggest that plants have evolved traits or mechanisms that reduce the generalism-benefit trade-off observed in nature.