---
title: "Pollen competition"
author: "Fernando Cagua, Hugo Marrero, Jason Tylianakis, Daniel Stouffer"
bibliography: references.bib
csl: ecology-letters.csl
output: pdf_document
header-includes:
  - \usepackage{booktabs}
  - \usepackage{setspace}
---

\doublespacing

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE)
options(xtable.comment = FALSE, 
        xtable.caption.placement = 'bottom',
        xtable.size = 'small',
        booktabs = TRUE)
```

## Abstract

## Introduction

## Methods

### Data collection

We performed sampling in three locations, each located in a distinct phytogeograohic region of the Argentinean Pampas (Figure 1). 
The sampling locations are distributed across a gradient of precipitation with a humid temperate climate in the eastward Flooding Pampas and an drier as we move inland and westward towards the Pampean Grasslands.
Across all sites, annual mean temperatures range between 14.8 and 15.8 Celsius. 

In each location, we sampled two restored and two agricultural fragments. 
However, due to the lack of available sites in the Flooding Pampas, it was only possible to sample one restored site.
We visited each fragment in November 2010 and February 2011. 
In each of these visits we gathered information related to abundance, plant-pollinator visitation, pollen transfer, and pollen deposition.

Abbundance was estimated using two 50 m randomly located transects in each fragment. In a first sampling we counted all units of floral attraction taht were found in a 2 m wide strip. In a second sampling we counted and collected all floral visitors while walking at a pace of 10 m per minute [@Marrero2014; @Memmott1999]. 
We constructed quantitative visitation networks using information about the floral visitors collected during abundance transects [@Marrero2014]. 
In addition, we also constructed qualitative visitation networks during independent two hour observations of floral visits across each fragment.
We estimated pollen transfer by examining the pollen loads present on the collected floral visitors [@Marrero2017]. 
Where the pollen count on an individual was estimated to be less than 2,000 grains, we identified every grain to the species level whenever possible and to pollen complexes when it was not. 
When the pollen count was above 2,000 grains, we clasified approx. 50% of pollen and total pollen counts were extrapollated [@Bosch2009]. 
If more than 10 pollen grains from a plant species were identified, we assumed that pollination service between the plant and the pollinator existed. 
Finally, we analised pollen deposition in a subset of the plant community [@Marrero2016]. 
This subset comprised between three and nine of the most common entomophilus species that were flowering during the samplimg period while ensuring that the chosen species covered a wide range on a specialization-generalization gradient. 
In the selected plants we removed all flowers except buds that were expected to go into inflorecense on the next day. 
A quarter of these buds were bagged to prevent animal pollination. 
Two days after inflorecense, we analysed the pollen grains in the flowers' pistils and classified it between conspecific and heterospecific pollen. 

The reader can find more details about the study sites, the data collection, and laboratory protocols in Marrero *et al.* (2014, 2016, and 2017)\footnote{
This paper is almost entirely based on data that has already been published in separate units in Marrero et al. 2014, 2016, and 2017. 
Marrero et al. 2014 used visitation data and determined that land uses (agricultural vs. restored) was correlated to differences on the degree of specialization and richness of plants and pollinators.
Marrero et al. 2016 used pollen deposition data and determined that the pollination service (both the absolute number and the proportion of conspecific pollen deposited on stigmas) is reduced in agricultural communities when compared to restored communities.
Finally, Marrero et al. 2017 used pollen transfer networks and found that pollen diversity and pollination plant niche overlap (at the species level) is greater in agricultural communities. 
The increase on niche overlap was attributed to be positively associated with an increased abundance of exotic plants.
}.

### Data analysis

## Results

## Discussion

## References