---
title: "The pollination trade-off"
subtitle: "Supplementary materials"
author: "Fernando Cagua, Hugo Marrero, Jason Tylianakis, Daniel Stouffer"
documentclass: book
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
header-includes:
  - \usepackage{booktabs}
---

\renewcommand\thefigure{S\arabic{figure}}    
\setcounter{figure}{0}   

\renewcommand\thetable{S\arabic{table}}    
\setcounter{table}{0}   

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE)
options(xtable.comment = FALSE, 
        xtable.caption.placement = 'bottom',
        xtable.size = 'small',
        booktabs = TRUE)
```

```{r fig-deposition-logtransformed-or-not, fig.height = 2, fig.cap = "Distribution of stigmatic pollen density plotted in (A) a linear scale, and (B) a logarithmic scale (zero values not shown)."}
loadd(dep_frame, sites)

p1 <- dep_frame %>%
  mutate(pollen_category = paste(pollen_category, "pollen"), 
         treatment = if_else(treatment == 'closed', 'bagged', treatment)) %>%
  ggplot(aes(x = pollen_density, colour = treatment)) + 
  stat_density(geom = "line") +
  facet_wrap( ~ pollen_category, scales = "free") +
  pub_theme() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "pollen density (grains per stigma)", 
       colour = "flower treatment") +
  theme(legend.position = "top")
  
p2 <- p1 +
  scale_x_log10()

leg <- cowplot::get_legend(p1)

cowplot::plot_grid(remove_legend(p1), remove_legend(p2), 
                   labels = LETTERS[1:2], 
                   label_size = 8) %>%
  cowplot::plot_grid(leg, ., rel_heights = c(0.1, 0.9), ncol = 1)
```

```{r fig-deposition-gain-logtransformed-or-not, fig.height = 2, fig.cap = "Distribution of the difference on stigmatic pollen density between open and closed flowers for one of the bootstrap replicates used in the model sets. When (A) using directly the gain in pollen density and (B) when pollen density is log transormed prior to calculating the gain. "}
loadd(rep_1)

plot_dist <- function(fun){
    rep_1 %>%
      filter(scale == 'global', 
             var_trans == 'lin') %>%
      mutate_at(c('open', 'closed'), fun) %>% 
      ggplot(aes(x = open - closed, colour = pollen_category)) +
      stat_density(position = position_identity(), geom = "line") +
      pub_theme() +
      scale_color_brewer(palette = "Set1") +
    theme(legend.position = "top") + 
    labs(x = "gain in pollen density (open-closed)", 
         colour = "pollen type")
}

p <- list(function(x) exp(x)-1, I) %>%
  plyr::llply(plot_dist)

leg <- cowplot::get_legend(p[[1]])
cowplot::plot_grid(remove_legend(p[[1]]), remove_legend(p[[2]]), 
                   labels = LETTERS[1:2], 
                   label_size = 8,
                   ncol = 2) %>%
  cowplot::plot_grid(leg, ., rel_heights = c(0.1, 0.9), ncol = 1)
```

```{r fig-abundance-logtransformed-or-not, fig.height = 2, fig.cap = "Distribution of plant abundance as (A) raw counts of floral units across communities, and (B) after applying a data transformation in which the counts have been "}
loadd(plant_rel_abu, sites)

p1 <- plant_rel_abu %>%
  filter(scale == 'community', 
         var_trans == 'log') %>%
  inner_join(sites, by = 'site_name') %>%
  ggplot() +
  stat_density(aes(x = rab, colour = locality_name),
               position = position_identity(), geom = 'line') +
  # stat_density(aes(x = abu_tot_rel_log), geom = 'line') +
  scale_color_brewer(palette = "Set1") +
  pub_theme() +
  # guides(colour = guide_legend(title = 'locality'), linetype = guide_legend(title = 'land use')) +
  labs(colour = 'locality', x = 'relative abundance')

p2 <- plant_rel_abu %>%
  filter(scale == 'global', 
         var_trans == 'log') %>%
  distinct() %>%
  inner_join(sites, by = 'site_name') %>%
  ggplot(aes(x = abu)) +
  stat_density(position = position_identity(), geom = 'line') +
  scale_color_brewer(palette = "Set1") +
  pub_theme() +
  labs(x = 'abundance (floral units)')

cowplot::plot_grid(p2, p1, rel_widths = c(0.42, 0.58), labels = LETTERS[1:2], label_size = 8)
```

```{r table-species-gain-global, results = 'asis'}
loadd(significant_gain_global, significant_gain_site, sites)
glance_table(significant_gain_global) %>%
  select(recipient, estimate, statistic, p.value) %>%
  mutate(recipient = paste0('{\\emph{ ', recipient, '}}')) %>%
  rename(`p value` = p.value,
         `difference` = estimate,
         `plant species` = recipient) %>%
  xtable(caption = "\\label{tab:table-species-gain-global} Results of testing the alternative hypothesis that the conspecific pollen density in open flowers is greater than the density in bagged flowers. Tests were performed at the species level (across communities).") %>%
  print.xtable(sanitize.text.function = function(x) x)
```

```{r table-species-gain-site, results = 'asis'}
loadd(significant_gain_global, significant_gain_site, sites)
glance_table(significant_gain_site) %>%
  inner_join(sites, by = "site_name") %>%
  group_by(recipient) %>%
  mutate(n_sites = n_distinct(site_name)) %>%
  filter(n_sites > 1) %>%
  group_by() %>%
  mutate(site_name = paste(locality_name, land_use, fragment, sep = ' - '),
         recipient = paste0('{\\emph{ ', recipient, '}}')) %>%
  select(recipient, site_name, estimate, statistic, p.value) %>%
  rename(`p value` = p.value,
         `difference` = estimate,
         `plant species` = recipient, 
         `community` = site_name) %>%
  xtable(caption = "Results of testing the alternative hypothesis that the conspecific pollen density in open flowers is greater than the density in bagged flowers. Tests were performed at the community level. Only species present in more than one community are shown.", 
         label= "tab:table-species-gain-site") %>%
  print(sanitize.text.function = function(x) x)
```

```{r table-variation-across-sites, results='asis'}
loadd(consp_self)
consp_self %>%
  anova(test = "Chisq")  %>%
  xtable(caption = 'Analysis of variance of conspecific pollen density in bagged flowers (self pollination rate).  Density were modelled using a quasipoisson distribution. The model suggests that self-pollination rates are species dependent but not across.', 
         label = 'tab:table-variation-across-sites')
```

```{r fig-conspecific-per-site, fig.height = 7, fig.cap="Conspecific pollen density across plant species for different communities. Community names are abbreviated: AN stands for Anquilóo, LC for Las Chiclas, and SC for San Claudio."}
loadd(dep_frame, sites)
site_plots_conspecific <- dep_frame %>%
  filter(pollen_category == 'conspecific') %>%
  inner_join(sites, by = 'site_name') %>%
  mutate(recipient_short = shorten_sp_name(recipient)) %>%
  mutate(pollen_category = paste(pollen_category, "pollen"), 
         treatment = if_else(treatment == 'closed', 'bagged', treatment)) %>% 
  plyr::dlply('site_name', function(x){
    x %>%
      ggplot(aes(y = pollen_density + 1, x = recipient_short,
                 fill = treatment)) +
      geom_boxplot(size = 0.25, outlier.size = 0.5, outlier.stroke = 0.5) +
      scale_y_log10(breaks = c(10,100,1000)) +
      coord_flip() + 
      ggtitle(paste(x$locality[1], '-', x$land_use, x$fragment)) +
      pub_theme() +
      xlab(NULL) +
      ylab('pollen density') +
      scale_fill_brewer(palette = "Set1")
  })

legend <- cowplot::get_legend(site_plots_conspecific[[1]])
 
site_plots_conspecific <- site_plots_conspecific %>%
  plyr::llply(function(x) {
    x + theme(legend.position = 'none', 
              title = element_text(size = 6))
  })

site_plots_conspecific <- rlist::list.append(site_plots_conspecific, legend)

cowplot::plot_grid(plotlist = site_plots_conspecific, ncol = 3)

```

```{r fig-conspecific-per-plant, fig.height = 7, fig.cap="Conspecific pollen density across communities for different study species. Only species present in more than onse site are shown. Community names are abbreviated: AN stands for Anquilóo, LC for Las Chiclas, and SC for San Claudio; A, and R indicate that the community corresponded to an agricultural or reserve site respectively."}
loadd(dep_frame, sites)
plant_plots_conspecific <- dep_frame %>%
  filter(pollen_category == 'conspecific') %>%
  inner_join(sites, by = 'site_name') %>%
  mutate(recipient_short = shorten_sp_name(recipient)) %>%
  mutate(pollen_category = paste(pollen_category, "pollen"), 
         treatment = if_else(treatment == 'closed', 'bagged', treatment)) %>%
  group_by(recipient) %>%
  mutate(n_sites = n_distinct(site_name), 
         site_name = `str_sub<-`(site_name, 1, 3, value = ''), 
         site_name = str_replace_all(site_name, '_', ' - ')) %>%
  group_by() %>%
  filter(n_sites >= 2) %>%
  plyr::dlply('recipient', function(x){
    x %>%
      ggplot(aes(y = pollen_density + 1, x = site_name,
                 fill = treatment)) +
      geom_boxplot(size = 0.25, outlier.size = 0.5, outlier.stroke = 0.5) +
      scale_y_log10(breaks = c(10,100,1000)) +
      coord_flip() +
      ggtitle(paste(x$recipient[1])) +
      pub_theme() +
      xlab(NULL) +
      ylab('pollen density') +
      scale_fill_brewer(palette = "Set1")
  })

legend <- cowplot::get_legend(plant_plots_conspecific[[1]])

plant_plots_conspecific <- plant_plots_conspecific %>%
  plyr::llply(function(x) {
    x + theme(legend.position = 'none',
              title = element_text(size = 6))
  })

plant_plots_conspecific <- rlist::list.append(plant_plots_conspecific, legend)

cowplot::plot_grid(plotlist = plant_plots_conspecific, ncol = 3)
```

```{r fig-model-results, fig.height = 3, fig.cap = "Model coefficients"}
loadd(tidied_fixed)

tidied_fixed %>%
  filter(term != "(Intercept)" #, 
         # var_trans == 'log'
         ) %>%
  group_by(pollen_category,scale, model, var_trans, term) %>%
  summarise(estimate = first(estimate)) %>%
  group_by() %>%
  humanize() %>%
  ggplot(aes(x = estimate, 
             colour = pollen_category)) +
  geom_vline(xintercept = 0, linetype = 2, size = 0.25) +
  geom_freqpoly(# alpha = 0.25,
               position = position_identity(),
               draw_quantiles = c(0.5, 0.95, 0.05), 
               trim = F, 
               scale = "count",
               binwidth = 0.05, 
               geom = "line") +
  pub_theme() +
  facet_grid(scale ~ term + var_trans, scales = "free_x") +
  scale_color_brewer(palette = "Set1") +
  scale_fill_brewer(palette = "Set1") +
  theme(legend.position = "bottom")
```

```{r fig-random-intercepts, fig.height= 3, fig.cap = "Random effect intercepts"}
loadd(tidied_fixed, sites)

tidied_fixed %>%
  separate("level", c("site_name", "plant_name"), sep = "/", remove = F) %>%
  filter(term == "(Intercept)" ,
         var_trans == 'log',
         scale == "community", 
         pollen_category == 'heterospecific'
         ) %>%
  humanize(sites) %>%
  ggplot(aes(x = estimate, colour = plant_name, group = level)) +
  geom_vline(xintercept = 0, linetype = 2, size = 0.25) +
  geom_freqpoly(size = 0.25) +
  facet_grid(locality_name + fragment ~ land_use) +
  pub_theme() +
  theme(legend.position = 'none')
```

```{r table-aic-random-models, results= 'asis'}
loadd(glanced_random)

summ <- glanced_random %>%
  filter(var_trans == "log") %>%
  group_by(pollen_category, scale, var_trans, model) %>%
  mutate(delta_AIC = AIC - min(AIC)) %>%
  group_by(pollen_category, scale, var_trans, random_effect) %>%
  summarise(AIC_50 = median(delta_AIC), 
            AIC_05 = quantile(delta_AIC, 0.05),
            AIC_95 = quantile(delta_AIC, 0.95)) %>% 
  mutate_if(is.numeric, round, digits = 1) %>% 
  mutate(delta_AIC = paste0(AIC_50, " [", AIC_05, ", ", AIC_95, "]")) %>%
  group_by() %>%
  humanize() %>%
  arrange(pollen_category, scale, random_effect) %>%
  rename(`pollen category` = pollen_category, 
         `random structure` = random_effect) 

contingency_table <- summ %>%
  # select(-var_trans) %>%
  ftable(row.vars = 4, col.vars = c(1, 2)) 
  
contingency_table[1:nrow(summ)] <- summ$delta_AIC

xtableFtable(contingency_table, method = "col.compact", 
             caption = paste('Comparison of the different random structures we considered. The table shows median delta AIC values of', n_distinct(glanced_random$model), "bootsrap resamples of the data. The 5th and 95th percentile are shown inside square brackets. Communities are defined by individual fragments but ignore the hierarchical arrangement of sampling sites."), 
         label = 'tab:table-aic-random-models')
```

```{r table-global-vs-community-models, results = 'asis'}
loadd(wilcox_glo_com)

wilcox_glo_com %>%
  filter(quality %in% c("rmse", "sigma"), 
         var_trans == "log") %>%
  select(quality, pollen_category, min_scale, estimate, p.value) %>%
  rename(`model metric` = quality,
         `pollen type` = pollen_category, 
         `best model set` = min_scale,
         `shift estimate` = estimate, 
         `p value` = p.value) %>%
  xtable(digits = -1, caption = "Results of two sample paired Wilcoxon signed rank test comparing the root mean square error and the residual standard deviation of the model sets constructed using predictors computed at the community or study level.", 
         label = "tab:table-global-vs-community-models")
```

