---
title: "ABC Analyses"
author: "Fernando Cagua"
date: "24 October 2017"
output: html_document
---
```{r setup, message=FALSE, results='hide'}
library(dplyr)
library(ggplot2)
library(ape)
library(magrittr)
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE,
                      fig.width = 8, 
                      fig.height = 6)

# read data
dep <- readRDS("../data/datasets/processed/all_deposition.rds")
dep_df <- plyr::ldply(dep, function(x){
  if(x$study == "marrero"){
    x$deposition %>%
    mutate(site = x$name, 
           study = x$study, 
           locality = x$locality, 
           land_use = x$land_use, 
           fragment = x$fragment)
  }
  
}) %>%
  mutate(pollen_category = recipient == donor,
         pollen_category = if_else(pollen_category, 
                                   "conspecific", 
                                   "heterospecific"),
         grain_density = n_grains/n_stigma)

deg <- readRDS("../data/datasets/processed/all_degree.rds")
deg_df <- plyr::ldply(deg, function(x){
  x$degree %>%
    mutate(study = x$study)
})
```


```{r}
theme_black = function(base_size = 12, base_family = "") {
 
  theme_grey(base_size = base_size, base_family = base_family) %+replace%
 
    theme(
      # Specify axis options
      axis.line = element_blank(),  
      axis.text.x = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.text.y = element_text(size = base_size*0.8, color = "white", lineheight = 0.9),  
      axis.ticks = element_line(color = "white", size  =  0.2),  
      axis.title.x = element_text(size = base_size, color = "white", margin = margin(10, 0, 0, 0)),  
      axis.title.y = element_text(size = base_size, color = "white", angle = 90, margin = margin(0, 10, 0, 0)),  
      axis.ticks.length = unit(0.3, "lines"),   
      # Specify legend options
      legend.background = element_rect(color = NA, fill = "black"),  
      legend.key = element_rect(color = "white",  fill = "black"),  
      legend.key.size = unit(1.2, "lines"),  
      legend.key.height = NULL,  
      legend.key.width = NULL,      
      legend.text = element_text(size = base_size*0.8, color = "white"),  
      legend.title = element_text(size = base_size*0.8, face = "bold", hjust = 0, color = "white"),  
      legend.position = "right",  
      legend.text.align = NULL,  
      legend.title.align = NULL,  
      legend.direction = "vertical",  
      legend.box = NULL, 
      # Specify panel options
      panel.background = element_rect(fill = "black", color  =  NA),  
      panel.border = element_rect(fill = NA, color = "white"),  
      panel.grid.major = element_line(color = "grey35"),  
      panel.grid.minor = element_line(color = "grey20"),  
      panel.margin = unit(0.5, "lines"),   
      # Specify facetting options
      strip.background = element_rect(fill = "grey30", color = "grey10"),  
      strip.text = element_text(size = base_size, margin = margin(t = 4, b = 4, r = 4, l = 4)),
      strip.text.x = element_text(color = "white"),  
      strip.text.y = element_text(color = "white",angle = -90),  
      # Specify plot options
      plot.background = element_rect(color = "black", fill = "black"),  
      plot.title = element_text(size = base_size*1.2, color = "white"),  
      plot.margin = unit(rep(1, 4), "lines")
 
    )
 
}
 
```


```{r}
# Calculate mean grain density over a grouping
mean_grain_density <- function(df, ...){
  gb_treat <- quos(..., treatment)

  df %>%
  group_by(!!!gb_treat) %>%
  summarise(mean_grain_density = mean(grain_density),
            sd_grain_density = sd(grain_density))
}

# Calculate difference between open and closed treatment within a grouping
calc_grain_diff <- function(df, ...){
  gb_treat <- quos(..., treatment)
  gb <- quos(...)
  
  mean_grain_density(df, ...) %>%
  group_by(!!!gb) %>%
  add_count() %>%
  filter(n == 2) %>%
  arrange(!!!gb_treat) %>%
  summarise(mean_grain_difference = mean_grain_density[2] - mean_grain_density[1],
            sd_grain_difference = sqrt(sd_grain_density[2]^2 + sd_grain_density[1]^2))
}

fragment_grain_density <- mean_grain_density(dep_df, locality, land_use, fragment, pollen_category, recipient)

open_treatment <- fragment_grain_density %>%
  filter(treatment == "open") %>%
  select(-sd_grain_density)

# order of plants
plant_order <- open_treatment %>% 
  filter(pollen_category == "conspecific") %>%
  group_by(recipient) %>%
  summarise(mean_grain_density = median(mean_grain_density)) %>%
  arrange(desc(mean_grain_density)) %$%
  recipient

open_treatment %>%
  group_by() %>%
  mutate(recipient = factor(recipient, levels = plant_order)) %>%
  ggplot(aes(x = recipient, y = mean_grain_density)) +
  facet_grid(pollen_category~., scales = "free")+
  geom_boxplot(colour = "white", fill = "black") +
  scale_y_log10(name = "# pollen grains per stigma") +
  xlab("") +
  theme_black(base_size = 18) +
  theme(axis.text.x = element_text(angle= 90, face = "italic"))

ggsave(filename = "boxplots.png", width = 13.3, height = 7.5)

fragment_grain_density %>%
  group_by() %>%
  mutate(recipient = factor(recipient, levels = plant_order), 
         treatment = factor(treatment, levels = c("open", "closed"), labels = c("open flowers ", "bagged flowers "))) %>%
  filter(pollen_category == "conspecific", 
         !is.na(recipient)) %>%
  ggplot(aes(x = recipient, y = mean_grain_density)) + 
  geom_boxplot(aes(fill = treatment, colour = treatment), alpha = 0.5) +
  scale_y_log10(name = "# pollen grains per stigma") +
  scale_fill_brewer(palette = "Pastel1", name = "", guide = guide_legend(title = NULL, direction = 'horizontal')) +
  	scale_colour_brewer(palette = 'Pastel1', name = "", guide = guide_legend(title = NULL, direction = 'horizontal')) +
  xlab("") +
  theme_black(base_size = 18) +
  theme(axis.text.x = element_text(angle= 90, face = "italic"), 
        legend.position = "top")
  
ggsave(filename = "boxplots-openclosed.png", width = 13.3, height = 7.5)

fragment_grain_diff <- calc_grain_diff(dep_df, locality, land_use, fragment, pollen_category, recipient)

fragment_grain_diff %>%
  select(-sd_grain_difference) %>%
  tidyr::spread(pollen_category, mean_grain_difference) %>%
  ggplot(aes(x = conspecific, y = heterospecific)) +
  geom_point(colour = "white") +
  geom_smooth(method = "lm", colour = "white") +
  scale_x_log10(name = "conspecific pollen gained with animal pollination") +
  scale_y_log10(name = "heterospecific pollen") +
  theme_black(base_size = 18)

ggsave(filename = "scatterplot-conspecific-heterospecifiv.png", width = 13.3, height = 7.5)


locality_grain_diff <- calc_grain_diff(dep_df, locality, pollen_category, recipient)
species_grain_diff <- calc_grain_diff(dep_df, pollen_category, recipient)

  
```

```{r}
fragment_grain_diff %>% 
  select(-sd_grain_difference) %>%
  mutate(mean_grain_difference = if_else(mean_grain_difference < 0, 0, mean_grain_difference)) %>% 
  tidyr::spread(pollen_category, mean_grain_difference) %>%
  left_join(deg_df, by = c("recipient" = "plant_name")) %>% 
  mutate(relationship = conspecific/(heterospecific + conspecific)) %>% 
  filter(.id != "emer") %>% 
  ggplot(aes(x = degree, y = relationship)) +
  geom_point(colour = "white") +
  geom_smooth(method = "glm", color = "white") +
  scale_x_log10(name = "number of partners") + 
  scale_y_continuous(name = "quality of animal pollination", labels = scales::percent) +
  theme_black(base_size = 18)

ggsave(filename = "scatterplot-efficiency.png", width = 13.3, height = 7.5)


```
sd

