---
title: "The pollination trade-off"
subtitle: "Workng doccument - questions & observations"
author: "Fernando Cagua, Hugo Marrero, Jason Tylianakis, Daniel Stouffer"
date: "3/1/2018"
output: 
  bookdown::pdf_document2: 
    keep_tex: no
    number_sections: false
toc: false
header-includes:
  - \usepackage{setspace}
  - \usepackage{xr}
  - \externaldocument[M-]{manuscript}
---

\onehalfspacing

## Summary of previous research using this data

This paper is almost entirely based on data that has already been published in separate units in Marrero et al. 2014, 2016, and 2017. 
Marrero et al. 2014 used visitation data and determined that land uses (agricultural vs. restored) was correlated to differences on the degree of specialization and richness of plants and pollinators.
Marrero et al. 2016 used pollen deposition data and determined that the pollination service (both the absolute number and the proportion of conspecific pollen deposited on stigmas) is reduced in agricultural communities when compared to restored communities.
Finally, Marrero et al. 2017 used pollen transfer networks and found that pollen diversity and pollination plant niche overlap (at the species level) is greater in agricultural communities. 
The increase on niche overlap was attributed to be positively associated with an increased abundance of exotic plants.

## To do 

* Include more explanatory variables to the model. In particular I want to include i. visitation rates, ii. uniqueness on flower traits (as it's been hypothesized that coflowering species with similar traits facilitate each other more), iii. the overlap in the pollen transfer space (pollinator pollen loads), and maybe something related to pollinator preferences. What do you think? Should I ditch one of this, should I include more? I want to keep it as simple as possible though. 
* Calculate degree of facilitation per species and include it in Figure 2A
* References to the introduction
* Correlation between explanatory variables to make sure they are not colinear
* Nail down discussion

## Questions

* Is the framing in the introduction appropiate? Should I highlight some other things? Mute down others? I wrote it thinking about a general audience reading a multidisciplinary journal. We should be able to improve it more once we decide on potential outlets 
* Which aspects from the results you think are more noteworthy? What should I empasize in the discussion? 
* Current analyses are done using 100 randomisations. Should I scale it up to 1000? Increasing from 30 to 100 did not change things much.
* I'm not convinced about the relevance of including the "within community/across communities" dimension to the study. I'm not sure it brings much to the story at all. Perhaps is just distracting? If not I'm also dubious about the way I'm comparing model sets. I used NRMSE, which agrees with other indices like $R^2$ and $\omega^2$. Other indices like $\sigma$ and RMSE provide different results and agree with previous results that show that heterospecific pollen deposition is more related to species specific trats than to community level variables. Any suggestion? 
* Unsure about the way I'm estimating temporal overlap between plant species? Daniel suggested to use some decomposition method and similar approaches to the ones used on trait analysis and estimate indices like originality and differentiation. There are only five surveys, so few "traits" so I'm not sure the data is suitable. Plus it's a more complicated method than Pianka's. 
