---
title: "The pollination trade-off"
subtitle: "Supplementary information"
author: "Fernando Cagua, Hugo Marrero, Jason Tylianakis, Daniel Stouffer"
# bibliography: references.bib
csl: ecology-letters.csl
documentclass: book
nocite: | 
  @Xu2003, @Nakagawa2013
output: 
  bookdown::pdf_document2: 
    keep_tex: yes
    toc: false
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
editor_options: 
  chunk_output_type: console
---

<!-- To add an S before each figure and table -->
\renewcommand\thefigure{S\arabic{figure}}    
\setcounter{figure}{0}   

\renewcommand\thetable{S\arabic{table}}    
\setcounter{table}{0}   

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE)
options(xtable.comment = FALSE, 
        xtable.caption.placement = 'bottom',
        xtable.size = 'small',
        booktabs = TRUE, 
        knitr.kable.NA = "-")
```

```{r fig-deposition-log-transformed-or-not, fig.height = 2, fig.cap = "Distribution of stigmatic pollen density plotted in (A) a linear scale, and (B) a logarithmic scale (zero values not shown).", eval=F}
drake::loadd(fig_pollen_density)

leg <- cowplot::get_legend(fig_pollen_density[[1]])
cowplot::plot_grid(
  remove_legend(fig_pollen_density[[1]]),
  remove_legend(fig_pollen_density[[2]]), 
  labels = LETTERS[1:2], 
  label_size = 8) %>%
  cowplot::plot_grid(leg, ., rel_heights = c(0.1, 0.9), ncol = 1)
```

```{r fig-deposition-gain-log-transformed-or-not, fig.height = 1.8, fig.cap = "Distribution of the stigmatic pollen density for one of the bootstrap replicates used in the model sets. When (A) using directly the gain in pollen density and (B) when pollen density is log transormed (for the relative amount of conspecific pollen, density was log-transformed prior to calculating the gain).", eval=F}
drake::loadd(fig_pollen_density_diff)

leg <- cowplot::get_legend(fig_pollen_density_diff[[1]])
cowplot::plot_grid(
  remove_legend(fig_pollen_density_diff[[1]]), 
  remove_legend(fig_pollen_density_diff[[2]]), 
  labels = LETTERS[1:2], 
  label_size = 8,
  ncol = 2) %>%
  cowplot::plot_grid(leg, ., rel_heights = c(0.1, 0.9), ncol = 1)
```

```{r fig-abundance-logtransformed-or-not, fig.height = 1.65, fig.cap = "Distribution of plant abundance as (A) raw counts of floral units across communities, and (B) after applying a data transformation in which the counts have been log transformed and scaled to have a mean of zero and a standard deviation of one.", eval = F}
drake::loadd(fig_abundance)

cowplot::plot_grid(
  fig_abundance[[2]], 
  fig_abundance[[1]],
  rel_widths = c(0.42, 0.58), labels = LETTERS[1:2], label_size = 8)
```

```{r table-facilitation-models-general, results='asis'}
drake::loadd(facilitation_models)

broom::tidy(facilitation_models, conf.int = F) %>%
  dplyr::select(-p.value, -group) %>%
  dplyr::mutate(term = dplyr::case_when(
    # term == "(Intercept)" ~ "Intercept",
    term == "sd_(Intercept).plant_name:site_name" ~ "S.D. random intercept", 
    term == "sd_heterospecific.plant_name:site_name" ~ "S.D. random slope", 
    TRUE ~ term
  )) %>%
  dplyr::filter(term != "cor_(Intercept).heterospecific.plant_name:site_name") %>%
  knitr::kable("latex", 
               caption = "Summary of the model used to analyse the relationship between heterospecific and conspecific pollen", 
               digits = 3,
               booktabs = T,
               col.names = c("predictor", "estimate" ,"S.E.", "z-value")) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::group_rows(index = c("fixed component" = 2, 
                                   "random component (species:community)" = 2)) 
```

```{r table-facilitation-models-random, results='asis'}
drake::loadd(facilitation_random_effects)
drake::loadd(sites)

tbl_frame <- facilitation_random_effects %>%
 dplyr::inner_join(sites, by = "site_name") %>%
  dplyr::mutate(site_name = paste(locality_name, 
                                  land_use, 
                                  fragment, 
                                  sep = ' - ')) %>%
  dplyr::mutate_if(is.character, knitr:::escape_latex) %>%
  dplyr::mutate(plant_name = paste0("\\textit{", plant_name, "}")) %>%
  dplyr::select(plant_name, site_name, heterospecific, error)

tbl_frame %>%
  knitr::kable("latex", 
               digits = 4, 
               col.names = c("species name", "community", "slope", "S.E."), 
               caption = "Slope of the relationship between heterospecific and conspecific pollen for each species in their community (fixed effect + conditional effect). Community names are constructed by location - agricultural/restored - fragment number.", 
               booktabs = T, 
               linesep = "", 
               escape = F) %>%
  kableExtra::kable_styling(font_size = 8) 
```

```{r table-open-bagged-models-general, results = "asis"}
drake::loadd(open_bagged_model)

broom::tidy(open_bagged_model, conf.int = F) %>%
  dplyr::select(-p.value, -group) %>%
  dplyr::mutate(term = dplyr::case_when(
    # term == "(Intercept)" ~ "Intercept (bagged flower)",
    term == "treatmentopen" ~ "treatment (unbagged flower)",
    term == "sd_(Intercept).plant_name:site_name" ~ "S.D. random intercept", 
    term == "sd_treatmentopen.plant_name:site_name" ~ "S.D. random slope", 
    TRUE ~ term
  )) %>%
  dplyr::filter(term != "cor_(Intercept).treatmentopen.plant_name:site_name") %>%
  knitr::kable("latex", 
               caption = "Summary of the model used to analyse the relationship between conspecific pollen deposited in bagged and unbagged flowers (open to animal pollination).", 
               digits = 3,
               booktabs = T,
               col.names = c("predictor", "estimate" ,"S.E.", "z-value")) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::group_rows(index = c("fixed component" = 2, 
                                   "random component (species:community)" = 2)) 
```

```{r table-open-bagged-models-random, results='asis'}
drake::loadd(con_con_plot_df)

con_con_plot_df %>%
 dplyr::inner_join(sites, by = "site_name") %>%
  dplyr::mutate(site_name = paste(locality_name, 
                                  land_use, 
                                  fragment, 
                                  sep = ' - ')) %>%
  dplyr::mutate_if(is.numeric, round, digits = 0) %>%
  dplyr::mutate(open_ci = paste0("[", open_lower, ", ", open_upper, "]"), 
                closed_ci = paste0("[", closed_lower, ", ", closed_upper, "]")) %>%
  dplyr::mutate_if(is.character, knitr:::escape_latex) %>%
  dplyr::mutate(plant_name = paste0("\\textit{", plant_name, "}")) %>%
  dplyr::select(plant_name, site_name, closed_mid, closed_ci, open_mid, open_ci) %>%
  knitr::kable("latex", 
               col.names = c("species name", "community", "mean", "C.I.", "mean", "C.I."), 
               caption = "Amount of conspecific pollen deposited  in bagged and unbagged flowers (open to animal pollination) for each species in their community. Community names are constructed by location - agricultural/restored - fragment number.", 
               booktabs = TRUE, 
               linesep = "", 
               align = "llrlrl", 
               escape = FALSE) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::add_header_above(c(" " = 2, "bagged" = 2, "unbagged" = 2))
```

```{r table-aic-random-models, results= 'asis'}
drake::loadd(glanced_random, random_effects)

summ <- glanced_random %>%
  dplyr::filter(var_trans == "log", 
                scale == "community") %>%
  dplyr::group_by(pollen_category, scale, var_trans, model) %>%
  dplyr::mutate(delta_AIC = AIC - min(AIC)) %>%
  dplyr::group_by(pollen_category, scale, var_trans, random_effect) %>%
  dplyr::summarise(AIC_50 = median(delta_AIC), 
            AIC_05 = quantile(delta_AIC, 0.05),
            AIC_95 = quantile(delta_AIC, 0.95), 
            n = n()) %>% 
  dplyr::group_by() %>%
  dplyr::select(-var_trans) %>%
  dplyr::right_join(expand.grid(pollen_category = unique(.$pollen_category),
                        scale = unique(.$scale),
                        random_effect = unique(.$random_effect))) %>% 
  dplyr::mutate_if(is.numeric, round, digits = 1) %>% 
  dplyr::mutate(delta_AIC = AIC_50, 
                delta_AIC_CI = paste0("[", AIC_05, ", ", AIC_95, "]")) %>%
  dplyr::group_by() %>%
  humanize(random_effects = random_effects) %>%
  dplyr::filter(pollen_category %in% c("conspecific (absolute)", "heterospecific")) %>%
  dplyr::mutate(
    pollen_category = dplyr::if_else(
      pollen_category == "conspecific (absolute)", 
      "conspecific pollen", "heterospecific pollen"), 
    random_name = knitr:::escape_latex(random_name)) %>%
  dplyr::arrange(pollen_category, delta_AIC) %>%
  dplyr::rename(`pollen type` = pollen_category,
         `random structure` = random_name) 

summ %>%
  dplyr::select(`random structure`, delta_AIC, delta_AIC_CI) %>%
  kableExtra::kable("latex", 
               caption = paste('Comparison of the two random structures we considered for the models of conspecific and heterospecific pollen deposition. The table shows median $\\Delta$AIC values of', dplyr::n_distinct(glanced_random$model), "bootsrap resamples of the data. The 5th and 95th percentile are shown inside square brackets. Communities are defined by individual fragments but ignore the hierarchical arrangement of sampling sites."),
               col.names = c("random structure", "median", "C.I."),
               booktabs = TRUE, 
               escape = F) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::group_rows(index = c("conspecific pollen" = 2, 
                                   "heterospecific pollen" = 2)) %>%
  kableExtra::add_header_above(c(" " = 1, "$\\\\Delta$AIC" = 2), escape = F)
```

```{r table-species-gain-global, results = 'asis', eval=F}
drake::loadd(significant_gain_global, significant_gain_site, sites)

glance_table(significant_gain_global) %>%
  dplyr::select(recipient, estimate, statistic, p.value) %>%
  dplyr::mutate(recipient = paste0('{\\emph{ ', recipient, '}}')) %>%
  dplyr::rename(`p value` = p.value,
         `difference` = estimate,
         `plant species` = recipient) %>%
  knitr::kable("latex", 
    caption = "Results of testing the alternative hypothesis that the conspecific pollen density in open flowers is greater than the density in bagged flowers. Tests were performed at the species level (across communities).", 
    escape = FALSE, 
    booktabs = TRUE, 
    linesep = c("")) %>%
  kableExtra::kable_styling(font_size = 8)
```

```{r table-aic-fixed-models, results= 'asis', eval=T}
drake::loadd(model_formula_ranking)

model_formula_ranking$by_model_set %>% 
  dplyr::filter(scale == "community") %>%
  dplyr::mutate_if(is.numeric, round, digits = 1) %>%
  dplyr::mutate(delta_AIC_CI = paste0(" [", delta_AIC_quantile_05,
                                      " ,", 
                                      delta_AIC_quantile_95,
                                      "]")) %>% 
  dplyr::group_by() %>%
  humanize(formula_long = TRUE) %>%
  dplyr::filter(pollen_category %in% c("conspecific (absolute)", "heterospecific")) %>%
  dplyr::mutate(
    pollen_category = dplyr::if_else(
      pollen_category == "conspecific (absolute)", 
      "conspecific pollen", "heterospecific pollen")) %>% 
  dplyr::mutate(fixed_formula = paste("~", fixed_formula)) %>%
  dplyr::arrange(pollen_category, delta_AIC_rank) %>%
  dplyr::select(fixed_formula, delta_AIC, delta_AIC_CI) %>%
  dplyr::rename(`fixed structure` = fixed_formula) %>% 
  knitr::kable("latex", 
               col.names = c("fixed structure", "median", "C.I."),
               caption = paste('Comparison of the different fixed structures we consideredfor the models of conspecific and heterospecific pollen deposition. The table shows median $\\Delta$AIC values of', dplyr::n_distinct(glanced_random$model), "bootsrap resamples of the data. The 5th and 95th percentile are shown inside square brackets."),
               booktabs = TRUE) %>%
  kableExtra::kable_styling(font_size = 8) %>%
  kableExtra::group_rows(index = c("conspecific pollen" = 15, 
                                   "heterospecific pollen" = 15)) %>%
  # kableExtra::collapse_rows(columns = 1, latex_hline = "major", valign = "middle") %>%
  kableExtra::add_header_above(c(" " = 1, "$\\\\Delta$AIC" = 2), escape = F)
```
 
```{r fig-correlation, fig.height = 4.5, fig.cap = "Corelation between the explanatory variables included in the statistical models.", eval=T}
drake::readd(fig_correlation)
```
 
```{r fig-model-results, fig.height = 7, fig.cap = "Distribution of effect estimates for models of conspecific and heterospecific pollen density gain. Only results for the models with the most parsimonous fixed effects.", eval=T}
drake::readd(fig_all_model_results)
```


```{r table-species-gain-site, results = 'asis', eval=F}
drake::loadd(significant_gain_global, significant_gain_site, sites)
table_frame <- glance_table(significant_gain_site) %>%
 dplyr::inner_join(sites, by = "site_name") %>%
  dplyr::group_by(recipient) %>%
  dplyr::mutate(n_sites = dplyr::n_distinct(site_name)) %>%
  dplyr::filter(n_sites > 1) %>%
  dplyr::group_by() %>%
  dplyr::mutate(site_name = paste(locality_name, land_use, fragment, sep = ' - '),
         recipient = paste0('{\\emph{ ', recipient, '}}')) %>%
  dplyr::select(recipient, site_name, estimate, statistic, p.value) %>%
  dplyr::rename(`p value` = p.value,
         `difference` = estimate,
         `plant species` = recipient, 
         `community` = site_name)

seps <-dplyr::if_else(table_frame$`plant species` == 
  dplyr::lag(table_frame$`plant species`), "", "\\addlinespace") %>%
  na.omit()

table_frame %>%
  knitr::kable("latex", 
    caption = "Results of testing the alternative hypothesis that the conspecific pollen density in open flowers is greater than the density in bagged flowers. Tests were performed at the community level. Only species present in more than one community are shown.", 
    escape = FALSE, 
    booktabs = TRUE, 
    linesep = seps, 
    digits = 3) %>%
  kableExtra::kable_styling(font_size = 8)
```

```{r table-variation-across-sites, eval=FALSE, results='asis', eval=F}
drake::loadd(consp_self)
consp_self %>%
  anova(test = "Chisq")  %>%
  knitr::kable("latex", 
    caption = 'Analysis of variance of conspecific pollen density in bagged flowers (self pollination rate).  Density were modelled using a quasipoisson distribution. The model suggests that self-pollination rates are species dependent but not across.',
    booktabs = TRUE) %>%
  kableExtra::kable_styling(font_size = 8)
```

```{r fig-global-community-correlations, fig.height = 2, fig.cap = "Relationship between the model's independent variables calculated at the community level and at the study-wide level.", eval=F}
drake::readd(fig_community_global_scatter)
```

```{r fig_effect_quant_qual, fig.height=3.5, fig.cap="asd", eval=F}
drake::loadd(fig_effect_quant_qual)

cowplot::plot_grid(
 fig_effect_quant_qual[[1]], 
 fig_effect_quant_qual[[2]],
  labels = LETTERS[1:2], 
  label_size = 8, ncol = 2)
```
