---
title: "PhD Timeline"
author: "Fernando Cagua"
date: "27 March 2017"
output: html_document
---

The aim is to finish as close to the 3 year mark as possible. The timing of the mid year breaks is unfortunate because it is likely to interrupt the progress of the PhD projects, the time lost due to the lack of momentum will be offset by the extra funding time. 

```{r, echo = FALSE, fig.height=1.9, message = FALSE, warning = FALSE, fig.cap= "Option A. Which includes a 3 month suspension during winter."}
source("../code/miscelaneous/schedule.R")
library(readr)

chart <- read_csv("../data/project_schedule_A.csv", 
									col_types = cols(start = col_date("%d/%m/%y"),
																	 mean = col_date("%d/%m/%y"),
																	 end = col_date("%d/%m/%y")))

plot_schedule(chart)
```

```{r, echo = FALSE, fig.height=2, message = FALSE, warning = FALSE, fig.cap= "Option B. Which includes 2 month break and 2 weeks at the iDiv school in Lepzig."}
chart <- read_csv("../data/project_schedule_B.csv", 
									col_types = cols(start = col_date("%d/%m/%y"),
																	 mean = col_date("%d/%m/%y"),
																	 end = col_date("%d/%m/%y")))

plot_schedule(chart)
```

```{r, echo = FALSE, fig.height=2.1, message = FALSE, warning = FALSE, , fig.cap= "Option A with a 6 month internship and a 2 month data camp."}
chart <- read_csv("../data/project_schedule_C.csv", 
									col_types = cols(start = col_date("%d/%m/%y"),
																	 mean = col_date("%d/%m/%y"),
																	 end = col_date("%d/%m/%y")))

plot_schedule(chart)
```